language: c++

os:
  - linux
  - osx

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake .
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .
  - cmake --build . -- -j2
