image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build

    cd build
    
    cmake c:\projects\source -G "Visual Studio 15"
    
    cmake --build . --config "Debug"

test_script:
- cmd: ctest -C Debug

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: HZl4Pq/cLyy+zdJ4Y4tJjavAXoavxw8GH7CyT3mVw5Pcn1DBSmKsCQ1rLYpI6n9V # your encrypted token from GitHub
  artifact: C:\projects\source\build\Debug\modio.dll;C:\projects\source\build\Debug\modio.lib            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
