image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build

    cd build
    
    cmake c:\projects\source -G "Visual Studio 15"
    
    cmake --build . --config "Debug"

test_script:
- cmd: ctest -C Debug

artifacts:
  - path: build\Debug\*.dll
    name: modio.dll

deploy:
  release: WindowsX-$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  force_update: true
  auth_token:
    secure: HZl4Pq/cLyy+zdJ4Y4tJjavAXoavxw8GH7CyT3mVw5Pcn1DBSmKsCQ1rLYpI6n9V # your encrypted token from GitHub
  draft: false
  prerelease: false
  tag: "Testag"
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
